package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.Car;

public class CarRepository extends RepositoryBase<Car> implements ICarRepository {

	public CarRepository(Connection connection, IMapResultSetIntoEntity<Car> mapper, IUnitOfWork uow) {
			super(connection, mapper, uow);
		}

	@Override
	protected void setInsert(Car entity) throws SQLException {
		insert.setString(1, entity.getVehtype());
		insert.setString(2, entity.getMake());
		insert.setString(3, entity.getModel());
		insert.setInt(4, entity.getYear());
	}

	@Override
	protected void setUpdate(Car entity) throws SQLException {
		update.setString(1, entity.getVehtype());
		update.setString(2, entity.getMake());
		update.setString(3, entity.getModel());
		update.setInt(4, entity.getYear());
		update.setInt(5, entity.getId());
	}

	@Override
	protected String tableName() {
		return "car";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE car("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "vehtype VARCHAR(20),"
				+ "make VARCHAR(20),"
				+ "model VARCHAR(20),"
				+ "year INT" 
				+ ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO car(vehtype,make,model,year) VALUES(?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE car SET vehtype=?, make=?, model=?, year=? WHERE id=?";
	}

	public List<Car> withYear(int year) {
		return null;
	}

}
