package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.Offer;

public class OfferRepository extends RepositoryBase<Offer> implements IOfferRepository {

	public OfferRepository(Connection connection, IMapResultSetIntoEntity<Offer> mapper, IUnitOfWork uow) {
			super(connection, mapper, uow);
		}

	@Override
	protected void setInsert(Offer entity) throws SQLException {
		insert.setString(1, entity.getTitle());
		insert.setString(2, entity.getDesc());
		insert.setDate(3, entity.getUploaded());
		insert.setInt(4, entity.getSeller_id());
		insert.setInt(5, entity.getCar_id());
	}

	@Override
	protected void setUpdate(Offer entity) throws SQLException {
		update.setString(1, entity.getTitle());
		update.setString(2, entity.getDesc());
		update.setDate(3, entity.getUploaded());
		update.setInt(4, entity.getSeller_id());
		update.setInt(5, entity.getCar_id());
		update.setInt(6, entity.getId());
	}

	@Override
	protected String tableName() {
		return "offer";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE offer("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "title VARCHAR(20),"
				+ "desc VARCHAR(50),"
				+ "uploaded DATE,"
				+ "seller_id INT,"
				+ "car_id INT"
				+ ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO offer(title,desc,uploaded,seller_id,car_id) VALUES(?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE offer SET title=?, desc=?, uploaded=?, seller_id=?, car_id=? WHERE id=?";
	}

	public List<Offer> withPrice(int price) {
		return null;
	}

}
