package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.Seller;

public class SellerRepository extends RepositoryBase<Seller> implements ISellerRepository {

	public SellerRepository(Connection connection, IMapResultSetIntoEntity<Seller> mapper, IUnitOfWork uow) {
			super(connection, mapper, uow);
		}

	@Override
	protected void setInsert(Seller entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setString(2, entity.getSurname());
		insert.setInt(3, entity.getTel_number());
		insert.setString(4, entity.getMail());
		insert.setString(5, entity.getTown());
		insert.setString(6, entity.getPost_code());
	}

	@Override
	protected void setUpdate(Seller entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setString(2, entity.getSurname());
		update.setInt(3, entity.getTel_number());
		update.setString(4, entity.getMail());
		update.setString(5, entity.getTown());
		update.setString(6, entity.getPost_code());
		update.setInt(7, entity.getId());
	}

	@Override
	protected String tableName() {
		return "seller";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE seller("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "surname VARCHAR(50),"
				+ "tel_number INT,"
				+ "mail VARCHAR(20),"
				+ "town VARCHAR(20),"
				+ "post_code VARCHAR(20)"
				+ ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO seller(name,surname,tel_number,mail,town,post_code) VALUES(?,?,?,?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE seller SET name=?, surname=?, tel_number=?, mail=?, town=?, post_code=? WHERE id=?";
	}

	public List<Seller> withTown(String town) {
		return null;
	}

}
